---
title: "Poems"
output:
  html_document:
    toc_float: true
nav_order: 1
has_children: true
---
***
_Introduction_

These poems are like a revision of histories

Of yours, of mine, of somebody's

They are triggers explained in cryptic themes

I pluck the root up to discover

My hands have dirt before

So I am trying to recover

All the feelings I felt in red before

***
## The ducks and Ama
_Audrey Yeo_, at the Rhine, Kleinbasel side, Switzerland (2021)

I asked the ducks in the water

If they have seen my Ama

If the water they touch, touched her

If the streams they brush their feathers with

Held all five of her fingers on each of her hand

and tell her... we haven't let her go

and we will one day return

and be hand in hand like

the younger me she would not let go...

I wonder how to reach her

Knowing she is buried down under ...

Will the coffin disintegrate

and rain dilute her to the waters

Will she meet me in Switzerland ?

Where we can be together



Will my Akung's words be true ?

When he said :

"_We will always be with you_"

I know the ducks pass by: "Hello stranger!...

...Do you know my Ama ? ... She was _my_ grandma"



A favourite parent: she liked safety, having enough for us to eat, being clean.

She kept the children healthy

When there was dengue.

Do you know her... little duckies?...

Because in a lot of ways, _I am so much like her_ 

... sturdy, efficient and I like numbers

Will you tell her when you see her to not let us go ?

I know she hates complainers 

but I just miss her so.

***
## The prey becomes the hunter
_Audrey Yeo_, Bankverein, Basel Stadt (2023)

The opened jar of butterflies

The hovering clouds of grey inside

The feet perched by her

Stabilizing the both of you

The Saccharine ways she was overdramatic and true

It was not a deceiving prose

She said she meant to say every single word

And yours spoke to block paths

Because you weren’t convince you deserved this much

Love and understanding has become confusing

To the brain damage that was done by the abusing

There, there, stay over there

She’s merely human so keep your truths and pick your dares

Wisely

For your lack of understanding has become abusive

Your honeyed words, they become self-serving

And the love you met on a Tuesday

May be more deserving

***
## Greater than a fortnight
_Audrey Yeo_, Theater Basel, Basel Stadt (2023)


I asked for symmetry between practice and punchlines

Seeing you distancing with icing

Telling me its still raining

I know of your form and its function

The consistent jokes that turn out to be escalation

But how could I have known

I would be short changed in return

Are you chasing two rabbits

And have you ended up with none ?

I guess, 

This grieving will be an easy recipe, 

Like in a fortnight or two

You will find flesh in flesh 

And I will vacillate in blue


***
## Diversity Candidate
_Audrey Yeo_, at Gundelingen, Basel City (2022)

I feel exposed

Like the wind caught me

Perforating my soul

Exposed I was two days ago

I am a solo trainee in this once in a lifetime journey

And while I move ahead I think I am slow

But are my frictions making traction or is speed my goal ?


I don't know if it's right to feel a certain instability

Like the world said I could come with

But it could also swallow me


My feet are perched but I feel them cycle in the air

I take flight and feel light but am never anywhere

Or is it that I've landed and I am having a ball

Or that I can feel safe now

But I don't know how to

Anymore

***
## Bye, "_Your Name_"

_Audrey Yeo_, at the SBB Basel, Switzerland (2023)

I can't read your message anymore

Your unilateral disclosure took me by surprise

Been reading and trying to parse it day and night

This week I finally understood the end of the last line

It said "_Bye_", followed by your name

So I naturally thought of all the ways I was to blame

So I traced my steps back to find the red flags

To find our thirty-nine-minute-phone-call the night before

Where you were gentle for when you were actually sore

Then at 7 am the next morning

Before I got up but was still in dreaming

And I read line by line to interpret the meaning

I laughed because it was all too shocking



It cannot be true

At the end of the first night

You turned back at the SBB and found me smiling at you

And your knees pointing to me the whole evening

Your goodwill and my sincerity looked like they were competing

Then to find the fault on a Sunday-two-hour-phone-call

We only heard earnesty and more

So it cannot be that

You sent me good morning messages after that


Come today I could parse the shock in my body

Your message came off first as a triggered mistake

What will I do with the growth I was inspired to make ?


And the consequences of this brings on 

A cinema of thoughts

You made it out like it was all my fault

If you complained about all the seeming defeat

I'm your Basel girl asking you to tell me all about it

Or is it that it is all too much

For a grown up who seems to be developing a crush

With your well-being in mind, should I reply ?

Because you've asked that I become irrelevant to you

For all of time


***
## To All My Lovers
_Audrey Yeo_, at _Famille Yeo_ in Basel City, Switzerland (2023)

This I promise to you all

That from now until the end of time

I may not always come from a place of strength

I will employ politeness and good manners

And all the conscience I can muster

Please forgive the oversights, I will have them

Please forgive the aberrations I make of the social contract 

I am finding out what kind of social being I am so,

This is a promise I make

For casual and lovely things

That accumulate in form and function

Being with good human beings

This time I am counting

All the ways to love

You all

And with the impending expiry is

I will remember more of your good will and deeds

So I will oversight your oversight

And see all the tries you make

Judge you only for your favourite mistakes - 

To all my lovers

I will know heartstrings exists

And solutions need waiting

While threads are threading 

until the last line -

I hope that I am a dream

Like many dreams you are after

and I hope that having had me

Makes your living a little easier 

***
## Missing information
_Audrey Yeo_, at _Famille Yeo_ in Basel City, Switzerland (2023)

I read the room correctly

And see what a haste you've made

The kind of irreversible and damaging, mistake

If we back-tracked

To see who hugged first and 

said we had the time

Then you'll have missing information

To find the good in your goodbye

***
## The Magic Green of the Rhine
_Audrey Yeo_, at the Rhine near Burgweg, Kleinbasel, Switzerland (2021)

I see how this goes

When things between us start ending

I see the river course reversing

The steps back are crushing


The retracting amount to hurt

You know it was you who waved at me first

I,

See how this goes

When things between us start ending


I saw the sun hit the river and it gloat

The magic green of the Rhine turned to a ghost ...

Destabilizing my universe,

I thought I shared bounds of land with you

And we were mastering our respective fools

A reflection of sun by water

My stature so short did I ever reach the magic river

But the ocean soon came out to dissolve

Green jade of glacier from our mountain tops

The empty expecting mirth

You laughed out loud

Excused by the afternoon wind

It paralyzes me so I can never win

I was drenched by river 

or so I thought

I was once your lover

and now I am not

***

## A letter to the "good guys"
_Audrey Yeo_, at Peter Rot Strasse 60, Basel City, Switzerland (2021), _revised_ at _Famille Yeo_ in Basel City (2023)

Someone please crystalise

The outline of my body

The punctuations of my story

For I have been scrambled way too much

to think that insults are a wanted human touch

To think and decipher who is on my side

But I end up trusting all the wretched guys

I need the shape and form and call my convictions content and the norm

I need a position like the punctuation in my tombstone

in this grave sentence

Where at the end of the prose

Those who are left should never speak the truth alone

Because ears captured my eventuality into sadness

and anger can find her way into kindness

I need the way to get there

If you would just listen and cease to merely stare

If you would just bear with my nights of wordsmithing

If you would just trust that you can do more than doing nothing

***
